# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    env:
      RAILS_ENV: test
      # Reservamos Seach API Configuration
      RESERVAMOS_SEARCH_API_BASE_URL: https://search.reservamos.mx
      RESERVAMOS_SEARCH_API_VERSION: v2
      RESERVAMOS_SEARCH_API_PREFIX: api

      # Open Weather API configuration
      OPEN_WEATHER_API_BASE_URL: https://api.openweathermap.org
      OPEN_WEATHER_API_VERSION: 2.5
      OPEN_WEATHER_API_PREFIX: data
      OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      # Add or replace test runners here
      - name: Run tests
        run: bundle exec rails test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      # Add or replace any other lints here
      - name: Lint Ruby files
        run: bundle exec rubocop
